### DISCUSSION TITLE
Process completed with exit code 1.

### DISCUSSION THREAD

**Discussion by lumynou5** [johnwason/vcpkg-action#13] [Q&A] [answered]
Sorry, I'm not familiar with GitHub Actions.
I'm trying to test the code automatically, but I got an error. I really don't understand what's wrong or what did I miss.

The workflow:
https://github.com/Luminous-Coder/merak16-asm/actions/runs/3853277885/jobs/6566120064

**Comment by johnwason** [comment, marked as answer]
You will need to also specify a `triplet` option. See the examples in the readme.

**Reply by lumynou5** [reply]
Are those three in the last section all the available triplets?

**Reply by johnwason** [reply]
There are many triplets available, you can run `vcpkg help triplet` to list them. You can also define your own triplets, see the vcpkg documentation. For linux you would typically use `x64-linux`

**Reply by lumynou5** [reply]
Thank you so much!!!

**Comment by Spongman** [comment]
I'm seeing the same error. I have the following:

```yaml
    - name: vcpkg build
      uses: johnwason/vcpkg-action@v4
      id: vcpkg
      with:
        manifest-dir: ${{ github.workspace }} 
        triplet: x86-windows-release
        token: ${{ github.token }}
```

and I get "Process completed with exit code 1." in the logs, but no other errors.


I also tried:
```

    - name: vcpkg build
      uses: johnwason/vcpkg-action@v4
      id: vcpkg
      with:
        pkgs: allegro5 zlib
        triplet: x86-windows-release
        token: ${{ github.token }}
```

with the same results
