### ISSUE TITLE
When I don't want to use the vcpkg installation package, with:pkgs: "", but report an error?

### ISSUE THREAD

**Issue by masx200** [johnwason/vcpkg-action#14]
When I don't want to use the vcpkg installation package, with:pkgs: "", but report an error?

**Comment by johnwason** [comment]
I have no idea what you are asking.

There is an issue that error messages may not be displayed due to the temporary file capturing output. It will be fixed sometime using `tee` when I have a chance.

**Comment by masx200** [comment]
```
Run export VCPKG_DEFAULT_BINARY_CACHE=/Users/runner/work/leetcode-test/leetcode-test/vcpkg_cache
  export VCPKG_DEFAULT_BINARY_CACHE=/Users/runner/work/leetcode-test/leetcode-test/vcpkg_cache
  mkdir $VCPKG_DEFAULT_BINARY_CACHE
  "/Users/runner/work/leetcode-test/leetcode-test/vcpkg/vcpkg" install --dry-run --triplet    > vcpkg_dry_run.txt
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    VCPKG_ROOT: /Users/runner/work/leetcode-test/leetcode-test/vcpkg
Error: Process completed with exit code 1.
```

**Comment by masx200** [comment]
```
- name: vcpkg-action

              uses: johnwason/vcpkg-action@v4
              with:
                   token: ${{ github.token }}
                   triplet: x64-osx-release
                   pkgs: ''
                   
```
